FROM postgres:16-alpine

ENV POSTGRES_USER=expenses_user
ENV POSTGRES_PASSWORD=expenses_password
ENV POSTGRES_DB=expenses_db

# vgradi shemo v image
COPY init.sql /docker-entrypoint-initdb.d/init.sql
